openvstorage/alba

- ocaml/src/alba_json.ml
- ocaml/src/cli_asd.ml
- ocaml/src/cli_maintenance.ml
- ocaml/src/cli_proxy.ml
when arakoon works with those compiler versions alba should too
(for now arakoon dies due to https://github.com/ocsigen/lwt/issues/170 , but that can easily be solved)
> fixes for silent breaking changes in ocaml 4.02.2/3

- cfg/maintenance_demo.json
(this changed when introducing priority on asd requests)
> default osd_timeout for maintenance process is 30 seconds

- setup/setup.ml
asds refused to start when they have `__warranty_void__write_blobs : null` in their config file
> fix test setup

- docker/alba_trisquel/Dockerfile
- docker/alba_ubuntu_mini/Dockerfile
the ubuntu needs ~290 MB
the trisquel needs ~233 MB
> Docker run

- cfg/asd_demo.json
- ocaml/src/automatic_repair.ml
It was a bit too trigger happy causing unnecessary load on environments that are doing no reads
> fix bug in auto-repair detection

- .projectile
- cfg/fragment_cache_config.json
- cfg/maintenance_demo.json
- cfg/proxy_demo.json
- ocaml/src/alba_client.ml
- ocaml/src/alba_client_download.ml
- ocaml/src/alba_json.ml
- ocaml/src/cli_maintenance.ml
- ocaml/src/cli_proxy.ml
- ocaml/src/fragment_cache.ml
- ocaml/src/fragment_cache_alba.ml
- ocaml/src/fragment_cache_config.ml
- ocaml/src/fragment_cache_config_test.ml
- ocaml/src/fragment_cache_test.ml
- ocaml/src/proxy_server.ml
- ocaml/src/test.ml
- setup/prul.ml
- setup/setup.ml
This pull request allows using e.g. a flash based alba as a fragment cache for a hard disk based alba.
Some more (related) changes are still to come in further pull requests:
- cache eviction
- extra statistics for the proxy
- configure cache on read/write behavior
- partial reads on the asds when no fragment cache is configured
- attempt to remove items from the fragment cache when removing/overwriting an object
> Alba accelerated alba

- ocaml/src/alba.ml
- ocaml/src/alba_bench.ml
- ocaml/src/asd_bench.ml
- ocaml/src/asd_server.ml
- ocaml/src/cli_asd.ml
- ocaml/src/cli_bench.ml
- ocaml/src/cli_bench_common.ml
- ocaml/src/cli_common.ml
- ocaml/src/cli_maintenance.ml
- ocaml/src/cli_messages.ml
- ocaml/src/cli_mgr.ml
- ocaml/src/cli_nsm_host.ml
- ocaml/src/cli_preset.ml
- ocaml/src/cli_proxy.ml
- ocaml/src/osd_bench.ml
- ocaml/src/proxy_bench.ml
- ocaml/src/tools/fsutil.ml
- bench blobs writing/reading (without network/rocksdb)
- fadvise random for partial read
- detached sendfile (as it could block, despite the earlier attempt at waiting for it to be readable)
- bench get-version (proxy & asd)
- asd bench exists
> Asd performance (benchmarking)

- .travis.yml
- travis.sh
- travis should fail if the unit tests fail (fixes a regression introduced in https://github.com/openvstorage/alba/pull/125)
- disable running the tests with tls (as they are broken since merging in #185)
> Travis updates

- ocaml/src/asd_test.ml
- ocaml/src/cli_asd.ml
This fixes #211 and prevents #197 from further happening.
Do note that asds where #197 has occurred will still not be able to be started after this change.
For that an update of rocksdb is needed, but still waiting on https://github.com/facebook/rocksdb/pull/881 to get into a new rocksdb release.
Once rocksdb has been updated the changes in this pull request can be reverted.
> no longer use rocksdb_recycle_log_file option

- ocaml/src/alba_json.ml
- ocaml/src/alba_osd.ml
- ocaml/src/alba_osd_test.ml
- ocaml/src/albamgr_protocol.ml
- ocaml/src/cli_asd.ml
- ocaml/src/cli_osd.ml
- ocaml/src/disk_failure_tests.ml
- ocaml/src/fragment_cache_alba.ml
- ocaml/src/nsm_host_protocol.ml
- ocaml/src/nsm_model.ml
- ocaml/src/osd_access.ml
- setup/setup.ml
- travis.sh
> use all ascii in names of generated namespaces

- ocaml/src/nsm_model.ml
This removes the failing assert, which isn't strictly necessary.
It is (was) there to detect buggy clients and prevent them from doing damage. In #307 it was observed that the check is incorrect, preventing valid uploads/repairs from succeeding.
It hasn't detected buggy clients in a long time, but maybe we still want to invest the time to make it work again as it should at a later time.
For now this fix should do.
> quick fix for #307

- ocaml/src/alba_osd_test.ml
- ocaml/src/albamgr_protocol.ml
- ocaml/src/osd_access.ml
```
2016-08-10 18:09:04 262746 +0200 - perf-roub-03 - 17640/0 - alba/proxy - 60 - info - Could not yet requalify osd 1, trying again in 1.000000 seconds: (Failure "attempting to use a resource from a pool which is being finalized"); backtrace:; Raised at file "format.ml", line 185, characters 41-52; Called from file "format.ml", line 427, characters 6-24
2016-08-10 18:09:04 471812 +0200 - perf-roub-03 - 17640/0 - alba/proxy - 61 - info - generic propagation ...: (Failure "attempting to use a resource from a pool which is being finalized"); backtrace:; Raised at file "queue.ml", line 86, characters 29-34; Called from file "src/tools/lwt_pool2.ml", line 98, characters 25-46
2016-08-10 18:09:04 471862 +0200 - perf-roub-03 - 17640/0 - alba/proxy - 62 - info - Unexpected exception in proxy …
```
> Don't invalidate alba_osd clients

- cpp/include/llio.h
- cpp/src/lib/llio.cc
This probably explains #320 and #321
> take eofbit into account too when evaluating state of an input/output stream

- ocaml/src/asd_server.ml
- ocaml/src/proxy_server.ml
- ocaml/src/tools/prelude.ml
related to #319 
should show if the exception comes from a malformed request or somewhere during processing of the request
> show where (index out of bounds) exceptions come from

- ocaml/src/alba_bench.ml
- ocaml/src/asd_bench.ml
- ocaml/src/cli_asd.ml
- ocaml/src/cli_bench.ml
- ocaml/src/cli_bench_common.ml
- ocaml/src/generic_bench.ml
- ocaml/src/osd_bench.ml
- ocaml/src/proxy_bench.ml
- `alba-bench` output of different clients to different files (and a process prefix)
(we might want this for the other benchmarks too)
- `multi-delete` allows you to clean up after a killed osd bench
> Bench improvements

- docker/ubuntu-14.04/Dockerfile
- docker/ubuntu-16.04/Dockerfile
#430 used a jenkins url with 'lastSuccessfulBuild' in it, these have a short lifetime.
Now using packages from a pinned build.
> fix for ubuntu 16.04 dockerfile

- .travis.yml
- docker/centos-7-verify/Dockerfile
- docker/centos-7/Dockerfile
- docker/ubuntu-14.04-verify/Dockerfile
- docker/ubuntu-16.04-verify/Dockerfile
- travis.sh
and fix the missing dependency it exposed for the centos-7 image
(also removed the travis caching effort as it doesn't work ... travis reports all cache as 0MB - so this was actually slowing down the builds)
> Verify all dockerfiles on travis

- docker/centos-7/Dockerfile
- docker/ubuntu-14.04/Dockerfile
- docker/ubuntu-16.04/Dockerfile
(and the ubuntu-14.04 one no longer segfaults due to large namespace ids)
> update to latest voldrv testers - now for centos-7 too

- ocaml/src/fragment_cache_alba.ml
Avoids clusters of this error:
```
Nov 15 01:56:00 ftcmp02 alba[28561]: 2016-11-15 01:56:00 296291 +0100 - ftcmp02 - 28561/0 - alba/proxy - 114259 - info - Exception while adding object to alba fragment cache: Albamgr_protocol.Protocol.Error.Albamgr_exn(4, "Albamgr_protocol.Protocol.Error.Namespace_already_exists"); backtrace:; Raised at file "queue.ml", line 68, characters 17-22; Called from file "src/tools/lwt_pool2.ml", line 98, characters 25-46
```
> catch ensure namespace race

- ocaml/src/fragment_cache_alba.ml
In case redis is unavailable the buffer would fill, and the blocking add would result in threads hanging.
This fixes #449.
> fix hanging threads in fragment cache

- ocaml/src/proxy_osd.ml
Had to answer some questions about proxy_osd behavior for kenneth/wim/stefaan and found this issue while verifying afterwards if I hadn't told any lies.
> sleep in requalify-endpoint loop of proxy_osd

- ocaml/src/alba_client_sequence.ml
- ocaml/src/alba_client_upload.ml
- ocaml/src/alba_osd.ml
- ocaml/src/proxy_server.ml
- setup/setup.ml
Also, it didn't clear the manifest cache when deleting an object, and this issue was present in the alba_osd code too. So extracted the commonalities and fixed that too.
> Fix #487 proxy apply_sequence doesn't update manifest cache

- ocaml/src/alba_client_namespace.ml
- ocaml/src/cli_common.ml
- ocaml/src/nsm_host_client.ml
- ocaml/src/osd_access.ml
- setup/setup.ml
See #427.
The added test could first reproduce this, and after the changes to message delivery on namespace creation it now succeeds (most of the time, see message about segfault below).
Of course @JeffreyDevloo will want to verify this too: you can find a fresh package @ http://10.100.129.100:8080/view/alba2/job/alba_docker_generic_package_ubuntu-16.04/lastSuccessfulBuild/artifact/alba_1.2.4-83-g9da540f_amd64.deb
In an unexpected turn of events the new test also allows reproducing a segfault which I still have to investigate - but which I believe to be unrelated to this pull request.
> Improvements related to #427

- ocaml/src/tools/networking2.ml
This may fix https://github.com/openvstorage/alba/issues/461.
There are some paths in (partial) download in which no timeouts are set, which could - in combination with the lack of tcp keepalive - explain #461.
> use default tcp keepalive for client connections

- ocaml/src/alba_test.ml
- ocaml/src/proxy_osd_test.ml
- ocaml/src/proxy_server.ml
- ocaml/src/proxy_test.ml
- ocaml/src/remotes.ml
the maintenance will still do it, and we don't depend on it for correct functioning of the proxy
> proxy shouldn't try to discover asds

- ocaml/src/cli_common.ml
- ocaml/src/cli_osd.ml
As requested in #629
```
$ ./alba get-osd-claimed-by -h 192.168.11.127 -p 8041 --verbose --to-json 2>/dev/null
{"success":false,"error":{"message":"(Failure \"I don't think this is an OSD\")","exception_type":"unknown","exception_code":0}}
$ ./alba get-osd-claimed-by -h 192.168.11.127 -p 8011 --verbose --to-json 2>/dev/null
{ "success": true, "result": "ebadb63d-79ff-4226-a53e-13a968bb4e0a" }
$ ./alba get-osd-claimed-by -h 192.168.11.127 -p 8011 --verbose --to-json 2>/dev/null
{ "success": true, "result": null }
```
> get-osd-claimed-by

- ocaml/src/disk_safety.ml
- ocaml/src/maintenance.ml
> maintenance should stop RewriteObject for deleted namespaces & disk safety smaller than -k makes no sense

- ocaml/src/osd_access.ml
- ocaml/src/remotes.ml
improvement (fix?) for #671 
@dejonghb saw an Osd_already_exists error coming back from the abm, after which the connection was closed, which lead me down this path...
> burn through less albamgr & nsm host & osd connections

- cfg/asd_demo.json
- cfg/maintenance_demo.json
- ocaml/src/cli_maintenance.ml
Not strictly necessary, but related to https://github.com/openvstorage/framework-alba-plugin/issues/378
> allow disabling listening for multicast messages from maintenance

- ocaml/src/tools/alba_partial_read_stubs.c
saw
```
Mar 29 15:54:25 ftcmp03 alba[17292]: 2017-03-29 15:54:25 445739 +0200 - ftcmp03 - 17292/0 - alba/asd - 15439 - info - server: exception occurred in client connection (172.22.186.32,48602): (Unix.Unix_error "Resource temporarily unavailable" partial_read;   /mnt/alba-asd/glrsTbu5QObLHo1P/70eLNFSsuOtkMn7cJwziBBvqBgUdhqt4/blobs/00/00/00/00/00/0e/e7/00000000000ee7f3)
```
on the env of @dejonghb 
Still waiting for jenkins and validation by @dejonghb
> fix for "resource temporarily unavailable" error during partial read

- ocaml/src/remotes.ml
Prevents constantly reconnecting to the albamgr e.g. in case a non existing preset was specified for the fragment cache
> less dropping of abm connections

- setup/setup.ml
before this change if a test run would fail without outputting new test results xml, this would result in silently using an old test results xml which was still there from a previous test run
> cpp test suite runner improvement

- ocaml/src/alba.ml
- ocaml/src/cli_common.ml
- ocaml/src/cli_osd.ml
should fix #773, #783 & openvstorage/alba_ee#82
> Various cli improvements
