openvstorage/alba

ocaml/myocamlbuild.ml
ocaml/src/alba.ml

git_revision: ....
git_repo: "https://github.com/openvstorage/alba.git"

which repo?

---

.travis.yml
README.md
travis.sh

just building for now, running tests is a next step

setting up travis build

---

Makefile
ocaml/src/access.ml
ocaml/src/alba_base_client.ml
ocaml/src/alba_client.ml
ocaml/src/albamgr_client.ml
ocaml/src/asd_client.ml
ocaml/src/asd_server.ml
ocaml/src/asd_test.ml
ocaml/src/cli_asd.ml
ocaml/src/cli_mgr.ml
ocaml/src/discovery.ml
ocaml/src/kinetic_client.ml
ocaml/src/nsm_host_client.ml
ocaml/src/proxy_server.ml
ocaml/src/remotes.ml
ocaml/src/tools/buffer_pool.ml
ocaml/src/tools/lwt_extra2.ml
ocaml/src/tools/networking2.ml
ocaml/src/tools/prelude.ml

this should improve memory usage + avoids some blitting

less output channels + use buffer_pool for all clients

---

ocaml/src/alba.ml
ocaml/src/alba_base_client.ml
ocaml/src/alba_client.ml
ocaml/src/alba_client_common.ml
ocaml/src/alba_client_download.ml
ocaml/src/alba_client_message_delivery.ml
ocaml/src/alba_client_namespace.ml
ocaml/src/alba_client_osd.ml
ocaml/src/alba_client_upload.ml
ocaml/src/alba_test.ml
ocaml/src/albamgr_access.ml
ocaml/src/cli_maintenance.ml
ocaml/src/disk_safety.ml
ocaml/src/disk_safety_test.ml
ocaml/src/maintenance.ml
ocaml/src/maintenance_common.ml
ocaml/src/maintenance_test.ml
ocaml/src/nsm_host_access.ml
ocaml/src/osd_access.ml
ocaml/src/proxy_server.ml
ocaml/src/rebalancing_helper.ml
ocaml/src/tools/object_reader.ml

refactoring of alba (base) client to make it significantly smaller

Alba client refactor

---

.gitignore
debian/changelog
fabfile/alba.py
fabfile/env.py
jenkins/cpp/010-build_client.sh
ocaml/src/alba.ml
ocaml/src/alba_base_client.ml
ocaml/src/alba_client.ml
ocaml/src/alba_client_osd.ml
ocaml/src/alba_test.ml
ocaml/src/albamgr_client.ml
ocaml/src/albamgr_plugin.ml
ocaml/src/albamgr_protocol.ml
ocaml/src/choose.ml
ocaml/src/cli_maintenance.ml
ocaml/src/cli_proxy.ml
ocaml/src/fragment_cache.ml
ocaml/src/fragment_cache_test.ml
ocaml/src/fragment_helper.ml
ocaml/src/maintenance.ml
ocaml/src/nsm_model.ml
ocaml/src/osd_access.ml
ocaml/src/proxy_server.ml
redhat/SPECS/alba.spec
travis.sh

required manually applying some of the patches, so might need more than a casual glance

Porting a bunch of bugfixes

---

cpp/Makefile
docker/alba_debian/Dockerfile
jenkins/cpp/010-build_client.sh

once you admit defeat, things become easy.

replacing tup with a primitive Makefile

---

Makefile
ocaml/src/albamgr_client.ml
ocaml/src/albamgr_plugin.ml
ocaml/src/albamgr_protocol.ml
ocaml/src/asd_test.ml
ocaml/src/automatic_repair.ml
ocaml/src/cli_maintenance.ml
ocaml/src/cli_mgr.ml
ocaml/src/maintenance.ml
ocaml/src/maintenance_config.ml
ocaml/src/maintenance_test.ml
ocaml/src/osd_access.ml

and also deprecate separate rebalance process

Automatic repair

---

docker/alba_debian_verify/Dockerfile

correct ci docker image for verify job

---

ocaml/src/cli_maintenance.ml

we want/need this for the multi geo setup

check osd claimed status on all nodes

---

ocaml/src/alba_client_message_delivery.ml
ocaml/src/alba_client_namespace.ml
ocaml/src/albamgr_client.ml
ocaml/src/albamgr_plugin.ml
ocaml/src/albamgr_protocol.ml
ocaml/src/nsm_host_client.ml
ocaml/src/nsm_host_plugin.ml
ocaml/src/nsm_host_protocol.ml
ocaml/src/plugin_extra.ml

(to avoid slow create namespace calls)

Batch message delivery

---

.travis.yml
fabfile/alba.py
fabfile/dev.py
ocaml/src/nsm_host_protocol.ml
ocaml/src/nsm_model.ml

+ run testsuite with tls enabled on travis

Bugfix for ssl

---

.gitignore
cfg/preset_no_checksums.json
ocaml/src/asd_config.ml
ocaml/src/asd_server.ml
ocaml/src/asd_test.ml
ocaml/src/cli_asd.ml
ocaml/src/cli_proxy.ml
setup/setup.ml

Add the dataloss guaranteed no_blobs option for asds (only to be used for testing purposes)

Asd no blobs

---

setup/setup.ml

Jenkins is all green again now

Fix a few broken tests

---

setup/setup.ml

This is what https://github.com/openvstorage/alba/pull/141 should've been

Fix compat tests

---

docker/alba_centos7_jenkins/Dockerfile
docker/alba_debian_jenkins/Dockerfile
travis.sh

need to wait for opam's caches to be updated before merging in though

update orocksdb version

---

docker/alba_centos7_jenkins/Dockerfile
ocaml/src/asd_server.ml

always listen to fadvise config

fix centos

---

ocaml/src/alba_base_client.ml
ocaml/src/alba_client.ml
ocaml/src/alba_test.ml
ocaml/src/asd_client.ml
ocaml/src/asd_protocol.ml
ocaml/src/asd_server.ml
ocaml/src/asd_test.ml
ocaml/src/cli_maintenance.ml
ocaml/src/cli_proxy.ml
ocaml/src/fragment_cache_alba.ml
ocaml/src/fragment_cache_config.ml
ocaml/src/fragment_cache_test.ml
ocaml/src/kinetic_client.ml
ocaml/src/osd.ml
ocaml/src/proxy_client.ml
ocaml/src/proxy_server.ml
ocaml/src/tools/llio2.ml
ocaml/src/tools/lwt_bytes2.ml
ocaml/src/tools/net_fd.ml

and use it when no fragment cache is configured

Implement asd partial read

---

ocaml/src/alba.ml
ocaml/src/alba_eviction.ml
ocaml/src/albamgr_client.ml
ocaml/src/maintenance.ml
ocaml/src/maintenance_coordination.ml
ocaml/src/tools/prelude.ml

Completely untested for now ...
I think I'll need an env anyway to see if this is enough?
I could still make the 60s checkup period and 1% eviction configurable?

Alba cache eviction

---

ocaml/src/tools/fsutil.ml
ocaml/src/tools/lwt_extra2.ml

even when you wait for the socket to become available

sendfile can EAGAIN

---

ocaml/src/fragment_cache.ml
ocaml/src/fragment_cache_test.ml
ocaml/src/tools/lwt_extra2.ml

proxy startup takes too long when removing a large fragment cache

fix for ovs-4456

---

setup/setup.ml

https://s3.amazonaws.com/archive.travis-ci.org/jobs/132479420/log.txt
```
running test test_buffer_pool.buffer_pool_test.all
running test test_coordinator_master.maintenance_coordination.all
running test test_coordinator_participants.maintenance_coordination.all
running test test_fallocate.posix_test.all
running test test_example_config.fragment_cache_config_test.all
2016/05/24 07:34:29 203186 +0000 - testing-gce-2223555b-76c1-43a3-ab12-3821f608d0f6 - 14901/0 - alba/unit-tests - 917074 - debug - rselect.select: ([6;4],[],0.001398) begin
2016/05/24 07:34:29 203202 +0000 - testing-gce-2223555b-76c1-43a3-ab12-3821f608d0f6 - 14901/0 - alba/unit-tests - 917075 - debug - rselect.select => ([4],[]) end
[38;5;2m[shell] [0mpgrep -f '/home/travis/build/openvstorage/alba/ocaml/alba.native …
```

tail proxy log file when smoke test fails

---

travis.sh

This will bring more clarity for what I actually wanted to know in https://github.com/openvstorage/alba/pull/205

cat testresults.xml on travis

---

docker/alba_debian_jenkins/Dockerfile
ocaml/src/albamgr_client.ml
ocaml/src/albamgr_plugin.ml
ocaml/src/albamgr_protocol.ml
setup/setup.ml

fix backwards compatibility with 0.9.5 and earlier

---

ocaml/src/alba.ml
ocaml/src/cli_asd.ml
ocaml/src/cli_bench.ml
ocaml/src/cli_common.ml
ocaml/src/cli_mgr.ml

Fixes the main reason https://github.com/openvstorage/alba/issues/229 was requested.

implement --to-json for a few more calls + some --help improvements

---

ocaml/src/cli_maintenance.ml
ocaml/src/cli_mgr.ml
ocaml/src/maintenance.ml
ocaml/src/nsm_model.ml
setup/prul.ml
setup/setup.ml

This exposed a bug in purging of osds and (a related) one in nsm update_manifest, both of which are now fixed

Test link unlink alba osd scenario

---

debian/changelog
redhat/SPECS/alba.spec

I would like to have #236 merged first

make_release: 0.9.8

---

ocaml/src/alba_osd.ml

fix connection leak

---

setup/setup.ml

I changed to __retry_timeout setting of the maintenance process to speed up the alba_as_osd suite, but as a side effect it has been making CI (mostly travis but also jenkins) less stable. This pull request improves upon the previous situation.

less annoying test failures on travis

---

ocaml/src/alba_test.ml
ocaml/src/cli_nsm_host.ml
ocaml/src/nsm_client.ml

regression was introduced in #219

test and fix for #266

---

GITBOOK.md
SUMMARY.md
docs/dependencies.md
docs/usingalba.md

https://openvstorage.gitbooks.io/alba/content/v/6c83eaf2fb5c4fdb81b69fafe3cbfa20f01a5550/

Quick setup and multiple fixes

---

cpp/src/examples/test_client.cc
cpp/src/lib/osd_access.cc
docker/alba_centos7_jenkins/Dockerfile
docker/alba_debian_jenkins/Dockerfile
travis.sh

respect the number of cores in config.
(I'm also expecting another bugfix, so we might stall a bit)

new gobjfs version

---

ocaml/src/asd_io_scheduler.ml
ocaml/src/asd_server.ml

throttle asd blob deletes

---

ocaml/src/albamgr_protocol.ml

cherry picked from rdma_problems

OsdInfo: also update transport

---

ocaml/src/maintenance.ml

found this bug while investigating #312, but haven't found the real cause of that issue yet

small fix in autorepair

---

cpp/include/generic_proxy_client.h
cpp/include/proxy_client.h
cpp/include/rdma_proxy_client.h
cpp/include/tcp_proxy_client.h
cpp/src/examples/test_client.cc
cpp/src/lib/generic_proxy_client.cc
cpp/src/lib/proxy_client.cc
cpp/src/lib/rdma_proxy_client.cc
cpp/src/lib/tcp_proxy_client.cc
cpp/src/tests/proxy_client_test.cc

Should fix #317 & #318 
@redlicha can you review?
(will test on 154.231)

Rdma proxy client fixes

---

cpp/include/alba_logger.h
cpp/src/examples/test_client.cc
cpp/src/lib/osd_access.cc

rora logging improvement

---

cpp/src/lib/manifest_cache.cc
cpp/src/tests/proxy_client_test.cc
ocaml/src/cli_asd.ml
ocaml/src/cli_common.ml
ocaml/src/cli_osd.ml
ocaml/src/tools/alba_rora_stubs.c
ocaml/src/tools/lwt_bytes2.ml

Rora server fixes

---

cpp/src/lib/lru_cache.h
cpp/src/lib/manifest_cache.cc
cpp/src/lib/manifest_cache.h

maybe @redlicha wants to have a look too.

per namespace LRU for manifest cache

---

ocaml/src/alba_base_client.ml
ocaml/src/alba_client.ml
ocaml/src/alba_client_download.ml
ocaml/src/alba_client_download_slices.ml
ocaml/src/manifest_cache.ml
ocaml/src/tools/object_reader2.ml

This fixes #371.
As a next step (building on these changes) I plan on implementing https://github.com/openvstorage/alba/issues/208 for the partial read path (that's where it's most important).

Refresh manifest on missing fragment

---

cpp/Makefile
cpp/include/llio.h
cpp/include/proxy_client.h
cpp/include/proxy_protocol.h
cpp/include/statistics.h
cpp/src/examples/test_client.cc
cpp/src/lib/manifest_cache.h
cpp/src/lib/osd_access.cc
cpp/src/lib/osd_access.h
cpp/src/lib/proxy_protocol.cc
cpp/src/lib/rora_proxy_client.cc
cpp/src/lib/rora_proxy_client.h
cpp/src/lib/statistics.cc

- null io
- io patterns (fixed, random, stride)
- small improvement to osd_access to let only 1 client do the fetching
- remove some high frequency log statements

Rora performance

---

cpp/src/lib/rdma_proxy_client.cc
docker/ubuntu-14.04/Dockerfile

basically moving some heavy stuff to the front so it could be cached.

address clang++ complaint; reorder package installation

---

ocaml/.merlin
ocaml/src/cli_proxy.ml

Closes https://github.com/openvstorage/alba/issues/362

Json of proxy cfg

---

ocaml/src/alba_test.ml
ocaml/src/maintenance.ml
ocaml/src/maintenance_coordination.ml
setup/setup.ml

only 1 maintenance process should repair a certain osd for a specific namespace

---

ocaml/src/asd_config.ml
ocaml/src/cli_asd.ml

configurable pool_size; default = 100

---

ocaml/src/alba.ml
ocaml/src/alba_json.ml
ocaml/src/disk_safety.ml
ocaml/src/disk_safety_test.ml
ocaml/src/tools/prelude.ml

Extend get disk safety output

---

ocaml/src/alba_json.ml

works around lack of https://github.com/whitequark/ppx_deriving_yojson/issues/19

output default values in json representation of presets

---

ocaml/src/cli_mgr.ml

added this to clean up some work items related to https://github.com/openvstorage/framework-alba-plugin/issues/252

allow marking work items as completed

---

ocaml/src/alba_client.ml
ocaml/src/alba_client_upload.ml
ocaml/src/nsm_host_access.ml
ocaml/src/nsm_host_plugin.ml

result of investigating #427 (now waiting on Jeffrey to provide me with new logs)

some logging improvements

---

jenkins/run2.sh

apparently I broke those in #453

fix verification jobs

---

ocaml/src/tools/prelude.ml

noticed something was wrong in https://github.com/openvstorage/alba/issues/441#issuecomment-263835263 and traced it back to this...

fix List.minima

---

ocaml/src/tools/lwt_extra2.ml

less frequent logging of short reads

---

ocaml/src/alba_json.ml
ocaml/src/cli_asd.ml
ocaml/src/cli_common.ml
ocaml/src/cli_mgr.ml
ocaml/src/cli_proxy.ml

more cli commands have --to-json option

---

ocaml/src/alba.ml
ocaml/src/alba_json.ml
ocaml/src/cli_asd.ml
ocaml/src/tools/prelude.ml

--to-json for asd-multi-get & download-object

---

ocaml/src/alba_client_message_delivery.ml

fix osd message delivery too far off

---

ocaml/src/asd_server.ml
ocaml/src/osd_kvs_test.ml

test assert asd small value + fix bug it exposes

---

ocaml/src/proxy_osd.ml

(equivalent of https://github.com/openvstorage/alba/pull/481)

fix proxy_osd test_assert

---

debian/changelog
ocaml/src/alba_client_sequence.ml
ocaml/src/alba_client_upload.ml
ocaml/src/alba_osd.ml
ocaml/src/proxy_server.ml
redhat/SPECS/alba.spec
setup/setup.ml

Fyi there were some conflicts with the lazy writeout changes...

1.2 for master

---

cfg/preset.json
cfg/preset_test.json
ocaml/src/alba_base_client.ml
ocaml/src/alba_client_download.ml
ocaml/src/alba_client_download_slices.ml
ocaml/src/alba_client_upload.ml
ocaml/src/alba_json.ml
ocaml/src/alba_test.ml
ocaml/src/disk_safety_test.ml
ocaml/src/encryption.ml
ocaml/src/fragment_helper.ml
ocaml/src/fragment_helper_test.ml
ocaml/src/fragment_size_helper_test.ml
ocaml/src/maintenance.ml
ocaml/src/maintenance_helper.ml
ocaml/src/maintenance_test.ml
ocaml/src/nsm_client.ml
ocaml/src/nsm_model.ml
ocaml/src/nsm_protocol.ml
ocaml/src/rebalancing_helper_test.ml
ocaml/src/recover_nsm_host.ml
ocaml/src/recovery_info.ml
ocaml/src/repair.ml
ocaml/src/test.ml
ocaml/src/tools/gcrypt.ml
ocaml/src/tools/gcrypt_test.ml
ocaml/src/tools/prelude.ml

- better fit for partial reads
- no padding needed for encryption

CTR mode encryption

---

ocaml/src/alba_client2.ml
ocaml/src/alba_osd.ml
ocaml/src/cli_asd.ml
ocaml/src/cli_osd.ml

improvement to alba_osd osd timeout configurability

---

ocaml/src/fragment_cache_alba.ml

Some more description in the code comment. Saw this problem on the env of @dejonghb.

be a bit more persistent about fragment cache namespace cleanup

---

cpp/include/alba_logger.h
cpp/include/boolean_enum.h
cpp/include/checksum.h
cpp/include/io.h
cpp/include/llio.h
cpp/include/manifest.h
cpp/include/osd_info.h
cpp/include/proxy_protocol.h
cpp/include/stuff.h
cpp/src/examples/test_client.cc
cpp/src/lib/alba_logger.cc
cpp/src/lib/lru_cache.h
cpp/src/lib/manifest.cc
cpp/src/lib/manifest_cache.h
cpp/src/lib/osd_info.cc
cpp/src/lib/proxy_protocol.cc
cpp/src/lib/rdma_proxy_client.cc
cpp/src/lib/tcp_proxy_client.cc
cpp/src/tests/llio_test.cc
cpp/src/tests/main.cc
cpp/src/tests/proxy_client_test.cc

clang sorts the includes these days.

make format

---

scriptlets/graph_it.py
scriptlets/osds_for_namespace.py
scriptlets/process.py

that might be a useful starting point when investigating problems

some scriptlets

---

ocaml/src/asd_server.ml

pointed out by @jeroenmaelbrancke

change asd stats log level

---

ocaml/src/alba_base_client.ml
ocaml/src/alba_client_message_delivery.ml
ocaml/src/alba_client_namespace.ml
ocaml/src/alba_client_upload.ml
ocaml/src/alba_test.ml
ocaml/src/proxy_osd.ml
ocaml/src/proxy_server.ml
setup/setup.ml

now it only dies due to a segfault ;-) ... (and no longer due to NoSatisfiablePolicy)
continuation of #501

expand stress2 test + stabilize

---

docker/centos-7-verify/Dockerfile
docker/centos-7/Dockerfile

Will wait for travis & http://10.100.129.100:8080/view/alba2/job/alba_docker_generic_ocaml/353/console to finish before merging

fix centos-7 dockerfile (new epel-release version)

---

ocaml/src/alba_base_client.ml
ocaml/src/alba_client_upload.ml
ocaml/src/nsm_model.ml
ocaml/src/repair.ml

preserve original timestamp on object rewrite

---

ocaml/src/alba_client_osd.ml

use stderr iso stdout when printing message

---

cpp/include/stuff.h
cpp/src/lib/asd_access.cc
cpp/src/lib/stuff.cc
cpp/src/lib/transport.cc
cpp/src/tests/asd_client_test.cc
cpp/src/tests/proxy_client_test.cc
docker/ubuntu-14.04/Dockerfile

- better function name
- make format
- cleanup commented code

minor cpp improvement

---

cpp/include/asd_access.h
cpp/src/lib/asd_access.cc
cpp/src/lib/osd_access.cc

report fast path failure for asd client

---

ocaml/src/cli_common.ml
ocaml/src/cli_proxy.ml
ocaml/src/proxy_protocol.ml
ocaml/src/proxy_server.ml

ability to forget namespaces in proxy statistics

---

ocaml/src/alba_test.ml
ocaml/src/albamgr_test.ml
ocaml/src/asd_test.ml
ocaml/src/disk_failure_tests.ml
ocaml/src/fragment_cache_test.ml
ocaml/src/fragment_helper_test.ml
ocaml/src/nsm_protocol_test.ml
ocaml/src/proxy_osd_test.ml
ocaml/src/proxy_test.ml
ocaml/src/tools/alba_wrappers.ml
ocaml/src/tools/alba_wrappers_stubs.c
ocaml/src/tools/test_extra.ml

Shows a file descriptor leak problem with our tests

track open fds in testcases

---

ocaml/src/alba_base_client.ml
ocaml/src/alba_client_download_slices.ml
ocaml/src/alba_client_namespace.ml
ocaml/src/alba_client_upload.ml
ocaml/src/alba_eviction.ml
ocaml/src/alba_test.ml
ocaml/src/cli_mgr.ml
ocaml/src/disk_failure_tests.ml
ocaml/src/maintenance.ml
ocaml/src/maintenance_helper.ml
ocaml/src/maintenance_test.ml
ocaml/src/nsm_model.ml
ocaml/src/rebalancing_helper.ml
ocaml/src/rebalancing_helper_test.ml
ocaml/src/recover_nsm_host.ml
ocaml/src/repair.ml
ocaml/src/tools/prelude.ml
ocaml/src/verify.ml

This should be a 'technical' refactoring. Other than a change of an internal data structure and the removal of some liberties in the tests, there should be no effect.

preparations

---

ocaml/src/osd_access.ml

This makes us leak way less (max < 600 fds) in test cases.

cancel refreshers on finalization

---

ocaml/src/tools/networking2.ml

don't leak when fail to connect

---

docker/ubuntu-14.04/Dockerfile
docker/ubuntu-16.04/Dockerfile

centos will follow (if/when it arrives)

voldrv 6.10 packages (contain alba 1.3.5)

---

ocaml/src/alba_json.ml
ocaml/src/cli_mgr.ml
ocaml/src/cli_proxy.ml

--to-json for proxy-list-namespaces & -list-objects

---

ocaml/src/alba_client_download.ml
ocaml/src/proxy_server.ml

don't log "Detected missing fragment..." for deleted objects

---

ocaml/src/disk_safety.ml

fix for race between namespace delete and get-disk-safety

---

ocaml/src/alba.ml
ocaml/src/albamgr_protocol.ml
setup/setup.ml

--to-json for list-namespace-osds

---

setup/setup.ml

We don't even know if it happens there or not.

check for bad address

---

cpp/src/lib/stuff.cc
cpp/src/tests/proxy_client_test.cc
ocaml/src/alba_client_upload.ml
ocaml/src/maintenance.ml
setup/setup.ml

Added a test related to https://github.com/openvstorage/alba/issues/645. Unfortunately it did not expose any issues.

Test broken fragment cache

---

ocaml/src/alba_eviction.ml
ocaml/src/maintenance.ml

add some (info) logging to maintenance eviction flow

---

ocaml/src/disk_safety.ml

catch another exception for race between namespace deletion & get-disk-safety

---

ocaml/src/alba_client_download.ml
ocaml/src/alba_statistics.ml
ocaml/src/alba_test.ml
ocaml/src/osd_access.ml
ocaml/src/osd_access_type.ml
ocaml/src/tools/lwt_bytes2.ml
ocaml/src/tools/prelude.ml

part of changes required for #660

deduplicate fragment fetch

---

cpp/src/tests/proxy_client_test.cc

assert after extra partial read

---

ocaml/src/osd_access.ml

fixes #664 
the other change suggested there is actually already logged as error

log osd disqualify as an error

---

ocaml/src/albamgr_client.ml
ocaml/src/nsm_host_client.ml
ocaml/src/tools/net_fd.ml
ocaml/src/tools/networking2.ml

There shouldn't be too many of these. And if somehow there are, we want it to be visible

log on info level when making a new connection

---

ocaml/src/osd_access.ml

combined with #674 this fully fixes #671

prevent a needless add-osd operation on the albamgr

---

ocaml/src/fragment_cache_fs.ml
ocaml/src/fragment_cache_test.ml

should (this time for sure) fix test.

optional sleep to make x_cache testable

---

ocaml/src/tools/lwt_extra2.ml

fixes #645, see my latest comment there

fix cpp test partial read broken fragment cache

---

cpp/include/asd_access.h
cpp/include/osd_access.h
cpp/include/proxy_client.h
cpp/src/lib/asd_access.cc
cpp/src/lib/osd_access.cc
cpp/src/lib/rora_proxy_client.cc
cpp/src/lib/rora_proxy_client.h
cpp/src/lib/tcp_transport.cc
cpp/src/tests/asd_client_test.cc
cpp/src/tests/proxy_client_test.cc

And if not fix it, at least fail after a more reasonable (and configurable) timeout

Attempt to fix operation canceled

---

debian/changelog
redhat/SPECS/alba.spec

make_release: 1.3.13

---

jenkins/run2.sh

Bash Issue in the jenkins bash script.

Grammatical Issue in bash

---

ocaml/src/alba_eviction.ml
ocaml/src/maintenance.ml

more aggressive cache eviction

---

ocaml/src/alba_client_download_slices.ml

This probably fixes #508, #617 & #681. At least on @dejonghb's env maintenance stopped segfaulting after this change.
Found this after @dejonghb was able to narrow it down to the 'chunk' buffer used for upload (during a rewrite object) being unsafed destroyed before/while data was still being read into the buffer (of course it only happens in an error path case).
Bert should have some improvements to the logging coming in another PR

fix use after free issue

---

Makefile
ocaml/src/alba_client_download.ml
ocaml/src/alba_client_upload.ml
ocaml/src/asd_client.ml
ocaml/src/asd_server.ml
ocaml/src/fragment_helper.ml
ocaml/src/maintenance.ml
ocaml/src/osd_access.ml
ocaml/src/other/posix_stubs.c
ocaml/src/recovery_info.ml
ocaml/src/tools/alba_crc32c_stubs.c
ocaml/src/tools/alba_wrappers_stubs.c
ocaml/src/tools/bytes_descr.ml
ocaml/src/tools/compressors.ml
ocaml/src/tools/hashes.ml
ocaml/src/tools/llio2.ml
ocaml/src/tools/lwt_bytes2.ml.cppo
ocaml/src/tools/lwt_extra2.ml
ocaml/src/tools/net_fd.ml

As @domsj predicted in  #705....

Log enhancements

---

Makefile
bin/alba
ocaml/src/alba.ml

[![asciicast](https://asciinema.org/a/0frfftd084lzq5ilo1oqd393s.png)](https://asciinema.org/a/0frfftd084lzq5ilo1oqd393s)

bash completion (first stab)

---

ocaml/src/fragment_cache.ml
ocaml/src/nsm_host_access.ml

prevent (Invalid_argument String.blit) exception due to blob getting unsafe_destroyed

make sure blob cannot get unsafe_destroyed

---

.travis.yml
jenkins/run2.sh

Partially addresses #720
(The actual problem on centos-7 isn't fixed yet)

Travis should fail on problems with the recovery test suite

---

.travis.yml
ocaml/myocamlbuild.ml
ocaml/src/tools/alba_gcrypt_stubs.c
ocaml/src/tools/gcrypt.ml

- allow grcrypt 1.5.3 (centos-7)
- on travis make recovery suite run in centos-7 container

Issue 720 older gcrypt

---

ocaml/src/alba_client_download.ml
ocaml/src/asd_client.ml
ocaml/src/asd_protocol.ml
ocaml/src/asd_server.ml
ocaml/src/cli_asd.ml
ocaml/src/maintenance.ml
ocaml/src/osd_access.ml
ocaml/src/osd_access_type.ml
ocaml/src/test.ml
ocaml/src/tools/alba_partial_read_stubs.c
ocaml/src/tools/llio2.ml
ocaml/src/tools/llio2_test.ml
ocaml/src/tools/networking2.ml
ocaml/src/tools/prelude.ml

A few todos

---

docker/centos-7/Dockerfile
docker/ubuntu-14.04/Dockerfile
docker/ubuntu-16.04/Dockerfile

merging this in will mean a new arakoon release as well (there, it was already merged in)

no longer use janestreet's opam repo

---

ocaml/src/alba_osd.ml

fix alba_osd disqualification due to race in message delivery

---

ocaml/src/osd_access.ml
setup/setup.ml

on ECONNREFUSED specifically and unknowns in general

don't spin 

---

cfg/preset_update.json
ocaml/src/alba_test.ml
ocaml/src/model/preset.ml
setup/setup.ml

backport of https://github.com/openvstorage/alba_ee/pull/34

allow update of preset's fragment size

---

cfg/preset_update2.json
ocaml/src/model/preset.ml
setup/setup.ml

Forgot to backport the related bugfix in https://github.com/openvstorage/alba/pull/758, so here it is

Fix preset fragment size update

---

ocaml/src/albamgr_client.ml
ocaml/src/cli_mgr.ml
ocaml/src/maintenance.ml
ocaml/src/nsm_host_access.ml
setup/setup.ml

fix list-namespaces-by-id --to-json output

---

ocaml/src/maintenance.ml

a cli addition to clean up already leaked objects is still to be written

fix object leak when deleting a global namespace

---

cfg/proxy_demo.json
ocaml/src/cli_proxy.ml

change and document defaults

---

ocaml/src/cli_maintenance.ml
ocaml/src/cli_proxy.ml
ocaml/src/fragment_cache_config.ml

minor cleanup

---

ocaml/src/asd_client.ml
ocaml/src/asd_test.ml
ocaml/src/automatic_repair.ml
ocaml/src/maintenance.ml
ocaml/src/test.ml
ocaml/src/tools/networking2.ml

travis & jenkins should be all green again now :-)

bugfix for test automatic repair

---

ocaml/src/fragment_cache_alba.ml

dedup create cache namespace

---

ocaml/src/nsm_model.ml
ocaml/src/proxy_protocol.ml

add last_updated field for proxy namespace stats

---

.gitignore
ocaml/src/alba_base_client.ml
ocaml/src/alba_client_download_slices.ml
ocaml/src/alba_client_preset_cache.ml
ocaml/src/alba_client_upload.ml
ocaml/src/alba_test.ml
ocaml/src/maintenance.ml
ocaml/src/maintenance_test.ml
ocaml/src/nsm_host_access.ml
ocaml/src/tools/prelude.ml

remove broken objects from cache namespaces

---

ocaml/src/alba.ml
ocaml/src/osd_keys.ml

cleanup command for leaked objects

---

ocaml/src/alba_client_upload.ml
ocaml/src/proxy_protocol.ml
ocaml/src/tools/lwt_extra2.ml

backport of https://github.com/openvstorage/alba_ee/pull/92

proxy statistics improvements (backport)

---

ocaml/src/alba_test.ml
ocaml/src/automatic_repair.ml
ocaml/src/maintenance_test.ml
ocaml/src/osd_access.ml
ocaml/src/osd_access_type.ml
ocaml/src/tools/lwt_extra2.ml

and a few other test run improvements

Further robustify test automatic repair

---

ocaml/src/tools/prelude.ml

The hypothesis is that when uploading a sequence through alba_osd in
case of early failure of one of the uploads the other threads continue
to upload asynchronously, while some of the resources required for this
are already being disposed. By waiting for all threads (instead of the
early exit on failure that was there before) this situation is avoided.

fix for blit invalid arg error
